### PR TITLE
Hardcode all our DNS names in /etc/hosts

### LINKED ISSUE #206: Configure `/etc/hosts` entries on backends
We have been having issues with flaky DNS inside the TPP backend. Specifically, failures from `git` with the error:
```
Could not resolve host: github-proxy.opensafely.org
```

Given that all the external services we talk to are hosted on a single, fixed IP (which must be fixed, for firewall configuration purposes) there's no point relying on external DNS for these and we should hardcode them in `/etc/hosts`.

Specifically, all of `{jobs,github-proxy,docker-proxy,collector}.opensafely.org` should point to `157.245.31.108`.

Note that the machine uses cloud-init, so it won't be sufficient to just update `/etc/hosts`.

To address the immediate issue, an entry for `github-proxy.opensafely.org` has been manually added to `/etc/hosts` and `/etc/cloud/templates/hosts.debian.tmpl`.

Related thread:
https://bennettoxford.slack.com/archives/C069YDR4NCA/p1708075680058539

### PR DESCRIPTION
**Pull request by bloodearnest**
This should improve reliability, and enable turning off external DNS
too.

Fixes #206

### CODE REVIEW

File: etc/opensafely/hosts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+## start opensafely dns
+
+# Hardcoded values for our core DNS names
+157.245.31.108 jobs.opensafely.org
+157.245.31.108 github-proxy.opensafely.org
+157.245.31.108 docker-proxy.opensafely.org
+157.245.31.108 collector.opensafely.org
```
Comment (madwort) [inline etc/opensafely/hosts:7]: better or worse?
```suggestion
157.245.31.108 jobs.opensafely.org github-proxy.opensafely.org docker-proxy.opensafely.org collector.opensafely.org
```

File: scripts/install.sh [hunk 2]
```diff
@@ -60,3 +60,15 @@ cp bin/otel-cli /usr/local/bin/
...
 systemctl reload ssh
+
+# hardcode /etc/hosts entries so we don't need DNS
+
+if grep -q "## start opensafely dns" /etc/hosts; then
+    # -z use NULL for new line, enables multiline matching
+    # first -e adds the current file content
+    # second -e removes the old file content
+    sed -z -e '/## start opensafely dns.*## end opensafely dns/r etc/opensafely/hosts' -e 's/## start opensafely dns.*## end opensafely dns//' -i.bak hosts
+else
```
Comment (madwort) [inline scripts/install.sh:71]: do we really need this? Could we simplify & just put a note in `etc/opensafely/hosts` saying "this file is managed automatically, do not edit"?

Comment (madwort) [reply scripts/install.sh:71]: hmmmm yeah but the defaults

**Comment by madwort** [comment]
in other news this will apply to all backends, but test-backend might need some tweaking 

``
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
#
```

File: scripts/install.sh (hunk 2 above)
Comment (bloodearnest) [reply scripts/install.sh:71]: right, that's why I kept it

Comment (madwort) [reply scripts/install.sh:71]: my pref would be putting the ubuntu default in something like `mybackend:/etc/hosts.default` or even `backend-server/etc/hosts` & concatting two files every time rather than attempting to `sed` the files, but I know you're going to hate that!

**Comment by bloodearnest** [comment]
> in other news this will apply to all backends, but test-backend might need some tweaking
> 
> ```
> # Your system has configured 'manage_etc_hosts' as True.
> # As a result, if you wish for changes to this file to persist
> # then you will need to either
> # a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
> # b.) change or remove the value of 'manage_etc_hosts' in
> #     /etc/cloud/cloud.cfg or cloud-config from user-data
> #
> ```

Hmm, yeah. I'm inclined to disable manage_etc_hosts on test backend, to make it match other backends?

**Comment by madwort** [comment]
> disable manage_etc_hosts on test backend

agree

File: scripts/install.sh (hunk 2 above)
Comment (bloodearnest) [reply scripts/install.sh]: I don't hate it, I'm just wary that the ubuntu default may be manipulated by other things

File: scripts/install.sh [hunk 3]
```diff
@@ -61,8 +61,13 @@ chmod a+rx /usr/local/bin
 
 systemctl reload ssh
 
-# hardcode /etc/hosts entries so we don't need DNS
+# disable cloud-init management of /etc/hosts
+if ! grep -q "manage_etc_hosts: false" /etc/cloud/cloud.cfg; then
```
Comment (madwort) [inline scripts/install.sh:65]: test-backend has overrides in `/etc/cloud/cloud.cfg.d/` - if TPP does as well we could do that & just write this direct into e.g. `/etc/cloud/cloud.cfg.d/999-opensafely`?

Comment (madwort) [reply scripts/install.sh:65]: interestingly, maybe we actually already have this set on test-backend in `/etc/cloud/cloud.cfg.d/90-digitalocean.cfg` & the contents of `/etc/hosts` is misleading?

Comment (bloodearnest) [reply scripts/install.sh:65]: Just saw that

bah

File: scripts/install.sh (hunk 2 above)
Comment (madwort) [reply scripts/install.sh]: well let's do it this way for now, we can always regret it later if we want.

**Review by madwort — APPROVED** [review]
