### PR TITLE
Enforce a single canonical location

### LINKED ISSUE #143: Create a canonical check out of backend-server on TPP/EMIS
Previously, the expectation was that multiple developers might git clone backend-server & run management commands from their personal clone. But this was unexpected & possibly makes it difficult to track any local fixups etc. Instead, we should use one canonical clone in a specified location, common to all backends.

### PR DESCRIPTION
**Pull request by bloodearnest**
The checkout of the backed-server repo should be /srv/backend-server

Fixes #143

### CODE REVIEW

**Review by madwort — APPROVED** [review]
nice. could we / should we attempt to enforce the location in the justfile too?

**Comment by madwort** [comment]
also - we should update the docs to tell people how to hold this

File: scripts/bootstrap.sh [hunk 1]
```diff
@@ -1,18 +1,26 @@
...
 fi
 
 echo "BACKEND_JUST=$1" > .env
 
 if [[ "$OSTYPE" == "linux-gnu"* ]]
 then
-  mv bin/just-1.14.0-x86_64-unknown-linux-musl /usr/local/bin/just
+  echo "Installing just in /usr/local/bin/just"
+  cp "$PWD/bin/just-1.14.0-x86_64-unknown-linux-musl" /usr/local/bin/just
   chmod 0755 /usr/local/bin/just
```
Comment (madwort) [inline scripts/bootstrap.sh:24]: open question - should we be doing this with `install` instead of `cp && chmod`? https://www.man7.org/linux/man-pages/man1/install.1.html

File: scripts/update-users.sh [hunk 2]
```diff
@@ -3,7 +3,7 @@ set -euo pipefail
 
 # files containing lists of gh user names for the different roles
 # note: probably will be API calls to job-server in future
-developers="developers"
+developers="${developers:-developers}"
```
Comment (madwort) [inline scripts/update-users.sh:6]: obligatory meme
developers developers developers

File: tests/install.sh [hunk 3]
```diff
@@ -1,16 +1,20 @@
...
 
 # run again to test idempotency
 ./scripts/install.sh
 
-. tests/utils.sh
+. "tests/utils.sh"
 
 # add test user that we know the key for
-./scripts/update-users.sh tests/developers
+developers=tests/developers ./scripts/update-users.sh test
```
Comment (madwort) [inline tests/install.sh:16]: yes, good spot

File: tests/install.sh [hunk 4]
```diff
@@ -1,16 +1,20 @@
...
+
 # Test install scripts
 ./scripts/install.sh
 ./scripts/update-users.sh developers
 
 # run again to test idempotency
 ./scripts/install.sh
 
-. tests/utils.sh
+. "tests/utils.sh"
```
Comment (madwort) [inline tests/install.sh:13]: huh?

**Review by madwort — APPROVED** [review]
looks good, couple of nits/questions

File: scripts/bootstrap.sh (hunk 1 above)
Comment (bloodearnest) [reply scripts/bootstrap.sh:24]: Good idea

File: README.md [hunk 5]
```diff
@@ -13,19 +13,31 @@ always having full administrative control of that environment, each
 backend is different in some way. We do try to minimise these
 differences, but they are unavoidable.
 
+## Initial Setup
+
+First time on a new backend machine, you need to do and initial checkout and bootsrap.
+
+```
+sudo mkdir -p /srv
```
[the remark this answers is not in the document]
Comment (bloodearnest) [reply README.md:21]: Hmm, we should probably refuse to run as anything but root?

[the remark this answers is not in the document]
Comment (bloodearnest) [reply README.md:21]: fixed

File: tests/install.sh (hunk 4 above)
Comment (bloodearnest) [reply tests/install.sh]: nfc, sorry! fixed
